
@router = http://testforexersise.s3-website.eu-north-1.amazonaws.com
@app    = http://localhost:3000
# @app  = https://<your-app-runner-id>.eu-north-1.awsapprunner.com


# Router
GET {{router}}/

### ROUTER menu file 
GET {{router}}/mainCode/menu.xml

### 2) VOICE WEBHOOK: (POST form-encoded)
POST {{app}}
Content-Type: application/x-www-form-urlencoded

From=%2B15551234567&To=%2B15557654321&CallSid=CA1234567890abcdef
