name: Auto Tag

on:
  push:
    branches: [ main ]

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Create tag
        id: tag
        run: echo `date +prod-%Y-%m-%d` >> $GITHUB_ENV

      - name: Push tag
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "Github Actions"
          git tag ${{ env.TAG }}
          git push origin ${{ env.TAG }}
